// Theme configuration for AAM Dashboard
export const themes = {
  terminal: {
    name: 'Terminal',
    colors: {
      bgMain: 'bg-slate-950',
      bgCard: 'bg-slate-900',
      bgCardHover: 'hover:bg-slate-800',
      border: 'border-slate-700',
      borderAccent: 'border-emerald-500/50',
      textPrimary: 'text-white',
      textSecondary: 'text-slate-400',
      textMuted: 'text-slate-500',
      accent: 'text-emerald-400',
      buttonPrimary: 'bg-emerald-500 hover:bg-emerald-400 text-slate-950',
      buttonSecondary: 'bg-slate-700 hover:bg-slate-600 text-white',
      buttonWarning: 'bg-yellow-600 hover:bg-yellow-500 text-white',
      buttonDanger: 'bg-red-600 hover:bg-red-500 text-white',
      buttonDisabled: 'bg-slate-700 cursor-not-allowed text-slate-400',
      gradientCard: 'from-emerald-900/30 to-slate-900',
      success: 'text-emerald-400',
      warning: 'text-yellow-400',
      error: 'text-red-400',
      scrollbarTrack: 'bg-slate-800',
      scrollbarThumb: 'bg-slate-600',
      inputBg: 'bg-slate-900',
      inputBorder: 'border-slate-600',
      inputFocus: 'focus:border-emerald-500',
    },
  },
  amber: {
    name: 'Amber',
    colors: {
      bgMain: 'bg-neutral-950',
      bgCard: 'bg-neutral-900',
      bgCardHover: 'hover:bg-neutral-800',
      border: 'border-neutral-800',
      borderAccent: 'border-amber-500/50',
      textPrimary: 'text-white',
      textSecondary: 'text-neutral-400',
      textMuted: 'text-neutral-500',
      accent: 'text-amber-500',
      buttonPrimary: 'bg-amber-500 hover:bg-amber-400 text-black',
      buttonSecondary: 'bg-neutral-800 hover:bg-neutral-700 text-white',
      buttonWarning: 'bg-yellow-600 hover:bg-yellow-500 text-white',
      buttonDanger: 'bg-red-600 hover:bg-red-500 text-white',
      buttonDisabled: 'bg-neutral-800 cursor-not-allowed text-neutral-500',
      gradientCard: 'from-amber-900/30 to-neutral-900',
      success: 'text-green-400',
      warning: 'text-amber-400',
      error: 'text-red-400',
      scrollbarTrack: 'bg-neutral-800',
      scrollbarThumb: 'bg-neutral-600',
      inputBg: 'bg-neutral-900',
      inputBorder: 'border-neutral-600',
      inputFocus: 'focus:border-amber-500',
    },
  },
  void: {
    name: 'Void',
    colors: {
      bgMain: 'bg-zinc-950',
      bgCard: 'bg-zinc-900/80',
      bgCardHover: 'hover:bg-zinc-800',
      border: 'border-zinc-800',
      borderAccent: 'border-cyan-500/50',
      textPrimary: 'text-white',
      textSecondary: 'text-zinc-400',
      textMuted: 'text-zinc-500',
      accent: 'text-cyan-400',
      buttonPrimary: 'bg-cyan-500 hover:bg-cyan-400 text-zinc-950',
      buttonSecondary: 'bg-zinc-800 hover:bg-zinc-700 text-white',
      buttonWarning: 'bg-yellow-600 hover:bg-yellow-500 text-white',
      buttonDanger: 'bg-red-600 hover:bg-red-500 text-white',
      buttonDisabled: 'bg-zinc-800 cursor-not-allowed text-zinc-500',
      gradientCard: 'from-cyan-900/30 to-zinc-900',
      success: 'text-cyan-400',
      warning: 'text-yellow-400',
      error: 'text-red-400',
      scrollbarTrack: 'bg-zinc-800',
      scrollbarThumb: 'bg-zinc-600',
      inputBg: 'bg-zinc-900',
      inputBorder: 'border-zinc-600',
      inputFocus: 'focus:border-cyan-500',
    },
  },
}
